[2024-01-12T18:57:23.232+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.format_to_parquet_task manual__2024-01-12T18:45:21.836625+00:00 [queued]>
[2024-01-12T18:57:23.240+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.format_to_parquet_task manual__2024-01-12T18:45:21.836625+00:00 [queued]>
[2024-01-12T18:57:23.242+0000] {taskinstance.py:2171} INFO - Starting attempt 2 of 2
[2024-01-12T18:57:23.249+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): format_to_parquet_task> on 2024-01-12 18:45:21.836625+00:00
[2024-01-12T18:57:23.254+0000] {standard_task_runner.py:60} INFO - Started process 986 to run task
[2024-01-12T18:57:23.263+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'format_to_parquet_task', 'manual__2024-01-12T18:45:21.836625+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpw354tv6y']
[2024-01-12T18:57:23.267+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask format_to_parquet_task
[2024-01-12T18:57:23.280+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-01-12T18:57:23.322+0000] {task_command.py:423} INFO - Running <TaskInstance: data_ingestion_gcs_dag.format_to_parquet_task manual__2024-01-12T18:45:21.836625+00:00 [running]> on host b70544739fe4
[2024-01-12T18:57:23.372+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_gcs_dag' AIRFLOW_CTX_TASK_ID='format_to_parquet_task' AIRFLOW_CTX_EXECUTION_DATE='2024-01-12T18:45:21.836625+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-12T18:45:21.836625+00:00'
[2024-01-12T18:57:25.319+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/data_ingestion_gcs_dag.py:37 DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
[2024-01-12T18:57:25.695+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 38, in format_to_parquet
    pq.write_table(table, src_file.replace('.csv.gz', '.parquet'))
  File "/home/airflow/.local/lib/python3.8/site-packages/pyarrow/parquet/core.py", line 3072, in write_table
    where, table.schema,
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'schema'
[2024-01-12T18:57:25.734+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=data_ingestion_gcs_dag, task_id=format_to_parquet_task, execution_date=20240112T184521, start_date=20240112T185723, end_date=20240112T185725
[2024-01-12T18:57:25.768+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 11 for task format_to_parquet_task ('DataFrame' object has no attribute 'schema'; 986)
[2024-01-12T18:57:25.817+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-12T18:57:25.867+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
