[2024-01-12T18:52:12.172+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.format_to_parquet_task manual__2024-01-10T22:48:23.203388+00:00 [queued]>
[2024-01-12T18:52:12.179+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.format_to_parquet_task manual__2024-01-10T22:48:23.203388+00:00 [queued]>
[2024-01-12T18:52:12.180+0000] {taskinstance.py:2171} INFO - Starting attempt 2 of 2
[2024-01-12T18:52:12.188+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): format_to_parquet_task> on 2024-01-10 22:48:23.203388+00:00
[2024-01-12T18:52:12.193+0000] {standard_task_runner.py:60} INFO - Started process 719 to run task
[2024-01-12T18:52:12.195+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'format_to_parquet_task', 'manual__2024-01-10T22:48:23.203388+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp0kyto9s5']
[2024-01-12T18:52:12.199+0000] {standard_task_runner.py:88} INFO - Job 8: Subtask format_to_parquet_task
[2024-01-12T18:52:12.211+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-01-12T18:52:12.239+0000] {task_command.py:423} INFO - Running <TaskInstance: data_ingestion_gcs_dag.format_to_parquet_task manual__2024-01-10T22:48:23.203388+00:00 [running]> on host b70544739fe4
[2024-01-12T18:52:12.289+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_gcs_dag' AIRFLOW_CTX_TASK_ID='format_to_parquet_task' AIRFLOW_CTX_EXECUTION_DATE='2024-01-10T22:48:23.203388+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-10T22:48:23.203388+00:00'
[2024-01-12T18:52:14.241+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/data_ingestion_gcs_dag.py:37 DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
[2024-01-12T18:52:14.606+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 38, in format_to_parquet
    pq.write_table(table, src_file.replace('.csv.gz', '.parquet'))
  File "/home/airflow/.local/lib/python3.8/site-packages/pyarrow/parquet/core.py", line 3072, in write_table
    where, table.schema,
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'schema'
[2024-01-12T18:52:14.632+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=data_ingestion_gcs_dag, task_id=format_to_parquet_task, execution_date=20240110T224823, start_date=20240112T185212, end_date=20240112T185214
[2024-01-12T18:52:14.645+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 8 for task format_to_parquet_task ('DataFrame' object has no attribute 'schema'; 719)
[2024-01-12T18:52:14.689+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-12T18:52:14.723+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
