[2024-01-12T18:57:54.338+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.format_to_parquet_task scheduled__2024-01-11T00:00:00+00:00 [queued]>
[2024-01-12T18:57:54.345+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.format_to_parquet_task scheduled__2024-01-11T00:00:00+00:00 [queued]>
[2024-01-12T18:57:54.346+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2024-01-12T18:57:54.358+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): format_to_parquet_task> on 2024-01-11 00:00:00+00:00
[2024-01-12T18:57:54.363+0000] {standard_task_runner.py:60} INFO - Started process 1025 to run task
[2024-01-12T18:57:54.365+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'format_to_parquet_task', 'scheduled__2024-01-11T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp_kv1mned']
[2024-01-12T18:57:54.369+0000] {standard_task_runner.py:88} INFO - Job 13: Subtask format_to_parquet_task
[2024-01-12T18:57:54.381+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-01-12T18:57:54.409+0000] {task_command.py:423} INFO - Running <TaskInstance: data_ingestion_gcs_dag.format_to_parquet_task scheduled__2024-01-11T00:00:00+00:00 [running]> on host b70544739fe4
[2024-01-12T18:57:54.457+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_gcs_dag' AIRFLOW_CTX_TASK_ID='format_to_parquet_task' AIRFLOW_CTX_EXECUTION_DATE='2024-01-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-11T00:00:00+00:00'
[2024-01-12T18:57:56.379+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/data_ingestion_gcs_dag.py:37 DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
[2024-01-12T18:57:56.777+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 38, in format_to_parquet
    pq.write_table(table, src_file.replace('.csv.gz', '.parquet'))
  File "/home/airflow/.local/lib/python3.8/site-packages/pyarrow/parquet/core.py", line 3072, in write_table
    where, table.schema,
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'schema'
[2024-01-12T18:57:56.834+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcs_dag, task_id=format_to_parquet_task, execution_date=20240111T000000, start_date=20240112T185754, end_date=20240112T185756
[2024-01-12T18:57:56.854+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 13 for task format_to_parquet_task ('DataFrame' object has no attribute 'schema'; 1025)
[2024-01-12T18:57:56.926+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-12T18:57:56.968+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
